version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=somepass
    ports:
      - 27017:27017
  db-seed:
    build: ./db-seed
    links:
      - mongodb